apiVersion: v1
kind: Pod
metadata:
  name: default-network
  annotations:
    networks: '[  
      { "name": "ovs-second-net" },
      { "name": "ovs-third-net" } 
   ]'
spec:  # specification of the pod's contents
  containers:
  - name: default-network
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
