apiVersion: v1
kind: Pod
metadata:
  name: default-network
spec:  # specification of the pod's contents
  containers:
  - name: default-network
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
